server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#注意 如果配置了spring.cloud.gateway.discovery.locator.enabled为true 即表示开启自动转发路由的功能
# 需要Eureka注册中心，开启此配置后，可通过Eureka注册中心注册的服务名通过网关转发
# 例：User微服务的接口：http://localhost:8083/getUserById?id=3，可通过gateway网关服务请求http://localhost:8081/USER/getUserById?id=3 转发到User微服务
# 如果User微服务带项目名 则请求网关服务也需要带上项目名：http://localhost:8083/user/getUserById?id=3 =》http://localhost:8081/USER/user/getUserById?id=3
      # 跨域配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        - id: user  # User服务1.0
          uri: lb://USER/**
          predicates:
            - Path=/gateway/user/**
            - Weight=UserService,5
          filters:
            - StripPrefix=2
        - id: weight # User服务2.0 # 实现灰度发布  Weight断言 定义同一个服务名为UserService，分配权重
          # 都通过localhost:8081/gateway/user/getPort 访问User服务和User2服务
          uri: lb://USER2/**
          predicates:
            - Path=/gateway/user/**
            - Weight=UserService,5
          filters:
            - StripPrefix=2
      default-filters:
        # 定义全局默认熔断过滤器
#        - name: Hystrix
#          args:
#            name: fallback
#            fallbackUri: forward:/gatewayfallback
        # 定义限流过滤器
        - name: RequestRateLimiter
          args:
            keyResolver: '#{@myRateLimiterResolver}' #使用Spring EL表达式 从容器中获取对象 '#{@beanName}'
            redis-rate-limiter.replenishRate: 1 # 生产令牌速度 每秒多少个令牌
            redis-rate-limiter.burstCapacity: 2 # 令牌桶容量

  redis:
    host: 172.16.98.100
    port: 6379
# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
#USER:
#  ribbon:
#    # 自定义负载均衡策略
#    NFLoadBalancerRuleClassName: com.lsh.gateway.config.MyLoadBanlanceRule

