server:
  port: 8084
spring:
  application:
    name: auth
  redis:
    host: 172.16.98.100
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/openapi?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/